language: c
dist: trusty

matrix:
    include:
        - os: linux
          env:
              - BUILD=x86_64-linux-gnu
              - EXECUTABLE=openocd
          addons:
              apt:
                  packages:
                      - patchutils
          compiler: gcc

        - os: linux
          env:
              - BUILD=i686-linux-gnu
              - CFLAGS=-m32
              - EXECUTABLE=openocd
          addons:
              apt:
                  packages:
                      - gcc-multilib patchutils
          compiler: gcc

        - os: linux
          env:
              - BUILD=x86_64-linux-gnu
              - EXECUTABLE=openocd
          addons:
              apt:
                  packages:
                      - patchutils
          compiler: clang

        - os: linux
          env:
              - BUILD=i686-linux-gnu
              - CFLAGS=-m32
              - CONFIGURE_ARGS="--disable-target64"
              - EXECUTABLE=openocd
          compiler: clang
          addons:
              apt:
                  packages:
                      - gcc-multilib patchutils

        - os: linux
          env:
              - BUILD=i686-w64-mingw
              - CONFIGURE_ARGS="--build=i686-unknown-linux-gnu --host=i686-w64-mingw32"
              - EXECUTABLE=openocd.exe
          compiler: i686-w64-mingw32-gcc
          addons:
              apt:
                  packages:
                      - binutils-mingw-w64-i686 gcc-mingw-w64-i686 g++-mingw-w64-i686 patchutils

script:
    # This is here for the signoff check.
    # Disabled because when travis does the integration build the last change
    # is an automated change, which won't have the Signed-off-by line.
    #- ./tools/checkpatch.sh

    # Ideally we'd diff back to where we either branched off OpenOCD or master,
    # or riscv. But that's tricky, and the default git clone only gets the last
    # 50 changes any case. Most merges won't consist of more than 40 changes,
    # so this should work fine most of the time, and be a lot better than not
    # checking at all.
    - git diff -U20 HEAD~40 |
        filterdiff -x "a/src/jtag/drivers/libjaylink/*" -x "a/tools/git2cl/*"
                -x "b/src/gnulib/*" |
        ./tools/scripts/checkpatch.pl --no-signoff -
    - ./bootstrap && ./configure --enable-remote-bitbang --enable-jtag_vpi $CONFIGURE_ARGS && make
    - file src/$EXECUTABLE
